inherit_from: .rubocop_todo.yml

AllCops:
    TargetRubyVersion: 2.4
    Exclude:
      - 'db/migrate/**/*'
      - 'db/schema.rb'
      - 'bin/**/*'

Rails:
    Enabled: true

Style/Alias:
    Enabled: false

Style/FrozenStringLiteralComment:
    Enabled: false

Style/NumericLiterals:
    Enabled: false

Layout/TrailingBlankLines:
    Enabled: false

Style/TrailingCommaInLiteral:
    EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
    Enabled: false

Style/Documentation:
    Enabled: false

Metrics/LineLength:
    Max: 80
    Exclude:
      - 'spec/**/*'
      - 'config/initializers/simple_form.rb'

Metrics/BlockLength:
    Exclude:
      - 'spec/**/*'
      - 'config/routes.rb'
